# Data Visualization with Modern Data Science

> Final

Yao-Jen Kuo <yaojenkuo@ntu.edu.tw> from [DATAINPOINT](https://www.datainpoint.com)

## Instructions

- Due to reduced capacity of mybinder.org, we use Google Colab instead.
- Save a copy for consistency by clicking the `Copy to Drive` button.
- If you accidentally delete some of the cells, just re-click the assignment link again for the original notebook.
- Write down your solution between comments `### BEGIN SOLUTION` and `### END SOLUTION`.
- Use current working directory as a relative path to import data.
- Running tests to see if your solutions are right:
    - Connect.
    - Runtime -> Restart and run all -> Yes -> Run anyway.
    - Scroll down to the bottom of notebook to see the test result.
- When you are ready to submit, click File -> Download .py.
- Rename the exported Python script with your student ID(e.g. `b01234567.py`) and upload to the Assignment session on NTU COOL.

In [ ]:
import unittest
import sqlite3
import numpy as np
import pandas as pd

In [ ]:
!wget -N "https://raw.githubusercontent.com/datainpoint/final-data-viz-with-modern-ds-ntu-spring-2022/main/nba.db"
!wget -N "https://raw.githubusercontent.com/datainpoint/final-data-viz-with-modern-ds-ntu-spring-2022/main/time_series_covid19_confirmed_global.csv"
!wget -N "https://raw.githubusercontent.com/datainpoint/final-data-viz-with-modern-ds-ntu-spring-2022/main/time_series_covid19_deaths_global.csv"

## 01. Define a Python function named `import_time_series_confirmed_deaths()` which imports `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` in working directory.

- Expected inputs: None.
- Expected outputs: `tuple`.

In [ ]:
def import_time_series_confirmed_deaths() -> tuple:
    """
    >>> time_series_confirmed, time_series_deaths = import_time_series_confirmed_deaths()
    >>> type(time_series_confirmed)
    pandas.core.frame.DataFrame
    >>> type(time_series_deaths)
    pandas.core.frame.DataFrame
    >>> time_series_confirmed.shape
    (285, 865)
    >>> time_series_deaths.shape
    (285, 865)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 02. Define a Python function named `transform_time_series_confirmed_deaths()` which transforms both `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` from wide format into long format.

- Expected inputs: None.
- Expected outputs: `tuple`.

In [ ]:
def transform_time_series_confirmed_deaths() -> tuple:
    """
    >>> time_series_confirmed_long, time_series_deaths_long = transform_time_series_confirmed_deaths()
    >>> type(time_series_confirmed_long)
    pandas.core.frame.DataFrame
    >>> type(time_series_deaths_long)
    pandas.core.frame.DataFrame
    >>> time_series_confirmed_long.shape
    (245385, 6)
    >>> time_series_deaths_long.shape
    (245385, 6)
    >>> print(time_series_confirmed_long)
           Province/State        Country/Region        Lat        Long     Date  \
    0                 NaN           Afghanistan  33.939110   67.709953  1/22/20   
    1                 NaN               Albania  41.153300   20.168300  1/22/20   
    2                 NaN               Algeria  28.033900    1.659600  1/22/20   
    3                 NaN               Andorra  42.506300    1.521800  1/22/20   
    4                 NaN                Angola -11.202700   17.873900  1/22/20   
    ...               ...                   ...        ...         ...      ...   
    245380            NaN    West Bank and Gaza  31.952200   35.233200  5/31/22   
    245381            NaN  Winter Olympics 2022  39.904200  116.407400  5/31/22   
    245382            NaN                 Yemen  15.552727   48.516388  5/31/22   
    245383            NaN                Zambia -13.133897   27.849332  5/31/22   
    245384            NaN              Zimbabwe -19.015438   29.154857  5/31/22   

            Confirmed  
    0               0  
    1               0  
    2               0  
    3               0  
    4               0  
    ...           ...  
    245380     657705  
    245381        535  
    245382      11822  
    245383     321779  
    245384     252398  

    [245385 rows x 6 columns]
    >>> print(time_series_deaths_long)
               Province/State        Country/Region        Lat        Long     Date  \
    0                 NaN           Afghanistan  33.939110   67.709953  1/22/20   
    1                 NaN               Albania  41.153300   20.168300  1/22/20   
    2                 NaN               Algeria  28.033900    1.659600  1/22/20   
    3                 NaN               Andorra  42.506300    1.521800  1/22/20   
    4                 NaN                Angola -11.202700   17.873900  1/22/20   
    ...               ...                   ...        ...         ...      ...   
    245380            NaN    West Bank and Gaza  31.952200   35.233200  5/31/22   
    245381            NaN  Winter Olympics 2022  39.904200  116.407400  5/31/22   
    245382            NaN                 Yemen  15.552727   48.516388  5/31/22   
    245383            NaN                Zambia -13.133897   27.849332  5/31/22   
    245384            NaN              Zimbabwe -19.015438   29.154857  5/31/22   

            Deaths  
    0            0  
    1            0  
    2            0  
    3            0  
    4            0  
    ...        ...  
    245380    5660  
    245381       0  
    245382    2149  
    245383    3987  
    245384    5503  

    [245385 rows x 6 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 03. Define a Python function named `merge_time_series_confirmed_deaths()` which merges the long formatted `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` into one data frame.

- Expected inputs: None.
- Expected outputs: `pandas.core.frame.DataFrame`.

In [ ]:
def merge_time_series_confirmed_deaths() -> pd.core.frame.DataFrame:
    """
    >>> merged_time_series = merge_time_series_confirmed_deaths()
    >>> type(merged_time_series)
    pandas.core.series.Series
    >>> merged_time_series.shape
    (245385, 7)
    >>> print(merged_time_series)
               Date Province/State        Country/Region        Lat        Long  \
    0       1/22/20            NaN           Afghanistan  33.939110   67.709953   
    1       1/22/20            NaN               Albania  41.153300   20.168300   
    2       1/22/20            NaN               Algeria  28.033900    1.659600   
    3       1/22/20            NaN               Andorra  42.506300    1.521800   
    4       1/22/20            NaN                Angola -11.202700   17.873900   
    ...         ...            ...                   ...        ...         ...   
    245380  5/31/22            NaN    West Bank and Gaza  31.952200   35.233200   
    245381  5/31/22            NaN  Winter Olympics 2022  39.904200  116.407400   
    245382  5/31/22            NaN                 Yemen  15.552727   48.516388   
    245383  5/31/22            NaN                Zambia -13.133897   27.849332   
    245384  5/31/22            NaN              Zimbabwe -19.015438   29.154857   

            Confirmed  Deaths  
    0               0       0  
    1               0       0  
    2               0       0  
    3               0       0  
    4               0       0  
    ...           ...     ...  
    245380     657705    5660  
    245381        535       0  
    245382      11822    2149  
    245383     321779    3987  
    245384     252398    5503  

    [245385 rows x 7 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 04. Define a Python function named `replace_nan_in_province_state()` which replaces the `np.nan` values in `Province/State` with `Country/Region` in the same row, while keeps the original values in `Province/State` if not `np.nan`.

- Expected inputs: None.
- Expected outputs: `pandas.core.frame.DataFrame`.

In [ ]:
def replace_nan_in_province_state() -> pd.core.frame.DataFrame:
    """
    >>> nan_replaced = replace_nan_in_province_state()
    >>> type(nan_replaced)
    pandas.core.frame.DataFrame
    >>> nan_replaced["Province/State"].isnull().sum()
    0
    >>> 
               Date        Province/State        Country/Region        Lat  \
    0       1/22/20           Afghanistan           Afghanistan  33.939110   
    1       1/22/20               Albania               Albania  41.153300   
    2       1/22/20               Algeria               Algeria  28.033900   
    3       1/22/20               Andorra               Andorra  42.506300   
    4       1/22/20                Angola                Angola -11.202700   
    ...         ...                   ...                   ...        ...   
    245380  5/31/22    West Bank and Gaza    West Bank and Gaza  31.952200   
    245381  5/31/22  Winter Olympics 2022  Winter Olympics 2022  39.904200   
    245382  5/31/22                 Yemen                 Yemen  15.552727   
    245383  5/31/22                Zambia                Zambia -13.133897   
    245384  5/31/22              Zimbabwe              Zimbabwe -19.015438   

                  Long  Confirmed  Deaths  
    0        67.709953          0       0  
    1        20.168300          0       0  
    2         1.659600          0       0  
    3         1.521800          0       0  
    4        17.873900          0       0  
    ...            ...        ...     ...  
    245380   35.233200     657705    5660  
    245381  116.407400        535       0  
    245382   48.516388      11822    2149  
    245383   27.849332     321779    3987  
    245384   29.154857     252398    5503  

    [245385 rows x 7 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 05. Define a Python function named `filter_taiwan_time_series()` which filters the data of `'Taiwan*'` from the output of `replace_nan_in_province_state()` and removes the asterisk `*` then format `Date` with ISO-8601 format `yyyy-mm-dd`(`%Y-%m-%d`).

- Expected inputs: None.
- Expected outputs: `pandas.core.frame.DataFrame`.

In [ ]:
def filter_taiwan_time_series() -> pd.core.frame.DataFrame:
    """
    >>> taiwan_time_series = filter_taiwan_time_series()
    >>> type(taiwan_time_series)
    pandas.core.frame.DataFrame
    >>> taiwan_time_series.shape
    (861, 7)
    >>> print(taiwan_time_series)
              Date Province/State Country/Region   Lat   Long  Confirmed  Deaths
    0   2020-01-22         Taiwan         Taiwan  23.7  121.0          1       0
    1   2020-01-23         Taiwan         Taiwan  23.7  121.0          1       0
    2   2020-01-24         Taiwan         Taiwan  23.7  121.0          3       0
    3   2020-01-25         Taiwan         Taiwan  23.7  121.0          3       0
    4   2020-01-26         Taiwan         Taiwan  23.7  121.0          4       0
    ..         ...            ...            ...   ...    ...        ...     ...
    856 2022-05-27         Taiwan         Taiwan  23.7  121.0    1735067    1784
    857 2022-05-28         Taiwan         Taiwan  23.7  121.0    1815703    1947
    858 2022-05-29         Taiwan         Taiwan  23.7  121.0    1892272    2056
    859 2022-05-30         Taiwan         Taiwan  23.7  121.0    1952355    2165
    860 2022-05-31         Taiwan         Taiwan  23.7  121.0    2032983    2255

    [861 rows x 7 columns]
    >>> (taiwan_time_series["Date"].astype(str).str.len() != 10).sum()
    0
    >>> taiwan_time_series["Province/State"].str.contains("*", regex=False).sum()
    0
    >>> taiwan_time_series["Country/Region"].str.contains("*", regex=False).sum()
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 06. Define a Python function named `calculate_daily_confirmed_deaths()` which calculates the column `daily_confirmed` and `daily_deaths` from the output of `filter_taiwan_time_series()`.

\begin{equation}
\text{daily}[i] = \text{cumulative}[i+1] - \text{cumulative}[i]
\end{equation}

- Expected inputs: None.
- Expected outputs: `pandas.core.frame.DataFrame`.

In [ ]:
def calculate_daily_confirmed_deaths() -> pd.core.frame.DataFrame:
    """
    >>> daily_confirmed_deaths = calculate_daily_confirmed_deaths()
    >>> type(daily_confirmed_deaths)
    pandas.core.frame.DataFrame
    >>> daily_confirmed_deaths.shape
    (861, 9)
    >>> print(daily_confirmed_deaths)
              Date Province/State Country/Region   Lat   Long  Confirmed  Deaths  \
    0   2020-01-22         Taiwan         Taiwan  23.7  121.0          1       0   
    1   2020-01-23         Taiwan         Taiwan  23.7  121.0          1       0   
    2   2020-01-24         Taiwan         Taiwan  23.7  121.0          3       0   
    3   2020-01-25         Taiwan         Taiwan  23.7  121.0          3       0   
    4   2020-01-26         Taiwan         Taiwan  23.7  121.0          4       0   
    ..         ...            ...            ...   ...    ...        ...     ...   
    856 2022-05-27         Taiwan         Taiwan  23.7  121.0    1735067    1784   
    857 2022-05-28         Taiwan         Taiwan  23.7  121.0    1815703    1947   
    858 2022-05-29         Taiwan         Taiwan  23.7  121.0    1892272    2056   
    859 2022-05-30         Taiwan         Taiwan  23.7  121.0    1952355    2165   
    860 2022-05-31         Taiwan         Taiwan  23.7  121.0    2032983    2255   

         daily_confirmed  daily_deaths  
    0                NaN           NaN  
    1                0.0           0.0  
    2                2.0           0.0  
    3                0.0           0.0  
    4                1.0           0.0  
    ..               ...           ...  
    856          94796.0         126.0  
    857          80636.0         163.0  
    858          76569.0         109.0  
    859          60083.0         109.0  
    860          80628.0          90.0  

    [861 rows x 9 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 07. Define a Python function named `filter_recent_pandemic_in_taiwan()` which filters the data from 2022-04-01 to the latest date.

- Expected inputs: None.
- Expected outputs: `pandas.core.frame.DataFrame`.

In [ ]:
def filter_recent_pandemic_in_taiwan() -> pd.core.frame.DataFrame:
    """
    >>> recent_pandemic_in_taiwan = filter_recent_pandemic_in_taiwan()
    >>> type(recent_pandemic_in_taiwan)
    pandas.core.frame.DataFrame
    >>> recent_pandemic_in_taiwan.shape
    (61, 9)
    >>> print(recent_pandemic_in_taiwan)
              Date Province/State Country/Region   Lat   Long  Confirmed  Deaths  \
    800 2022-04-01         Taiwan         Taiwan  23.7  121.0      23629     853   
    801 2022-04-02         Taiwan         Taiwan  23.7  121.0      24033     853   
    802 2022-04-03         Taiwan         Taiwan  23.7  121.0      24313     853   
    803 2022-04-04         Taiwan         Taiwan  23.7  121.0      24588     853   
    804 2022-04-05         Taiwan         Taiwan  23.7  121.0      24866     853   
    ..         ...            ...            ...   ...    ...        ...     ...   
    856 2022-05-27         Taiwan         Taiwan  23.7  121.0    1735067    1784   
    857 2022-05-28         Taiwan         Taiwan  23.7  121.0    1815703    1947   
    858 2022-05-29         Taiwan         Taiwan  23.7  121.0    1892272    2056   
    859 2022-05-30         Taiwan         Taiwan  23.7  121.0    1952355    2165   
    860 2022-05-31         Taiwan         Taiwan  23.7  121.0    2032983    2255   

         daily_confirmed  daily_deaths  
    800            235.0           0.0  
    801            404.0           0.0  
    802            280.0           0.0  
    803            275.0           0.0  
    804            278.0           0.0  
    ..               ...           ...  
    856          94796.0         126.0  
    857          80636.0         163.0  
    858          76569.0         109.0  
    859          60083.0         109.0  
    860          80628.0          90.0  

    [61 rows x 9 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 08. Define a Python function named `import_tables_in_nba_db()` which imports the tables `career_summaries`, `players`, and `teams` from `nba.db` in working directory.

- Expected inputs: None.
- Expected outputs: `tuple`.

In [ ]:
def import_tables_in_nba_db() -> tuple:
    """
    >>> career_summaries, players, teams = import_tables_in_nba_db()
    >>> type(career_summaries)
    pandas.core.frame.DataFrame
    >>> type(players)
    pandas.core.frame.DataFrame
    >>> type(teams)
    pandas.core.frame.DataFrame
    >>> career_summaries.shape
    (506, 31)
    >>> players.shape
    (506, 18)
    >>> teams.shape
    (30, 12)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 09. Define a Python function named `list_roster_of_the_nba_playoffs_2022()` which lists the roster of all playoff teams given `nba.db`.

```python
playoff_teams = ["PHX", "NOP", "DAL", "UTA", "GSW", "DEN", "MEM", "MIN", "MIA", "ATL", "PHI", "TOR", "MIL", "CHI", "BOS", "BKN"]
```

- Expected inputs: None.
- Expected outputs: `pandas.core.frame.DataFrame`.

In [ ]:
def list_roster_of_the_nba_playoffs_2022() -> pd.core.frame.DataFrame:
    """
    >>> roster_of_the_nba_playoffs_2022 = list_roster_of_the_nba_playoffs_2022()
    >>> type(roster_of_the_nba_playoffs_2022)
    pandas.core.frame.DataFrame
    >>> roster_of_the_nba_playoffs_2022.shape
    (269, 4)
    >>> print(roster_of_the_nba_playoffs_2022)
        confName tricode firstName    lastName
    0       East     ATL    Bogdan  Bogdanovic
    1       East     ATL  Chaundee   Brown Jr.
    2       East     ATL     Clint      Capela
    3       East     ATL    Danilo   Gallinari
    4       East     ATL  De'Andre      Hunter
    ..       ...     ...       ...         ...
    264     West     UTA      Rudy         Gay
    265     West     UTA      Rudy      Gobert
    266     West     UTA     Trent     Forrest
    267     West     UTA     Udoka    Azubuike
    268     West     UTA    Xavier       Sneed

    [269 rows x 4 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 10. Define a Python function named `list_roster_of_the_nba_finals_2022()` which lists the roster of the NBA Finals 2022, the Boston Celtics and the Golden State Warriors. Sort players with their career points per game.

- Expected inputs: None.
- Expected outputs: `pandas.core.frame.DataFrame`.

In [ ]:
def list_roster_of_the_nba_finals_2022() -> pd.core.frame.DataFrame:
    """
    >>> roster_of_the_nba_finals_2022 = list_roster_of_the_nba_finals_2022()
    >>> type(roster_of_the_nba_finals_2022)
    pandas.core.frame.DataFrame
    >>> roster_of_the_nba_finals_2022.shape
    (34, 5)
    >>> print(roster_of_the_nba_finals_2022)
       confName tricode  firstName          lastName   ppg
    0      East     BOS     Jayson             Tatum  20.9
    1      East     BOS     Jaylen             Brown  16.5
    2      East     BOS         Al           Horford  13.7
    3      East     BOS    Derrick             White  11.5
    4      East     BOS     Marcus             Smart  10.5
    5      East     BOS     Daniel             Theis   7.6
    6      East     BOS     Robert      Williams III   7.2
    7      East     BOS     Payton         Pritchard   6.9
    8      East     BOS        Nik          Stauskas   6.7
    9      East     BOS       Luke            Kornet   5.5
    10     East     BOS      Grant          Williams   5.4
    11     East     BOS      Aaron           Nesmith   4.2
    12     East     BOS    Brodric            Thomas   3.3
    13     East     BOS       Matt              Ryan   3.0
    14     East     BOS        Sam            Hauser   2.5
    15     East     BOS      Juwan            Morgan   1.5
    16     East     BOS      Malik             Fitts   1.3
    17     West     GSW    Stephen             Curry  24.3
    18     West     GSW       Klay          Thompson  19.5
    19     West     GSW     Andrew           Wiggins  19.3
    20     West     GSW     Jordan             Poole  13.7
    21     West     GSW      James           Wiseman  11.5
    22     West     GSW      Andre          Iguodala  11.4
    23     West     GSW       Otto        Porter Jr.  10.6
    24     West     GSW   Jonathan           Kuminga   9.3
    25     West     GSW   Draymond             Green   8.7
    26     West     GSW     Damion               Lee   8.2
    27     West     GSW    Nemanja           Bjelica   7.6
    28     West     GSW       Gary         Payton II   5.2
    29     West     GSW       Juan  Toscano-Anderson   4.8
    30     West     GSW      Kevon            Looney   4.7
    31     West     GSW      Moses             Moody   4.4
    32     West     GSW      Chris           Chiozza   3.3
    33     West     GSW  Quinndary      Weatherspoon   2.1
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## End of assignment, ignore the following cells.

In [ ]:
class TestFinal(unittest.TestCase):
    def test_01_import_time_series_confirmed_deaths(self):
        time_series_confirmed, time_series_deaths = import_time_series_confirmed_deaths()
        self.assertIsInstance(time_series_confirmed, pd.core.frame.DataFrame)
        self.assertIsInstance(time_series_deaths, pd.core.frame.DataFrame)
        self.assertEqual(time_series_confirmed.shape, (285, 865))
        self.assertEqual(time_series_deaths.shape, (285, 865))
    def test_02_transform_time_series_confirmed_deaths(self):
        time_series_confirmed_long, time_series_deaths_long = transform_time_series_confirmed_deaths()
        self.assertIsInstance(time_series_confirmed_long, pd.core.frame.DataFrame)
        self.assertIsInstance(time_series_deaths_long, pd.core.frame.DataFrame)
        self.assertEqual(time_series_confirmed_long.shape, (245385, 6))
        self.assertEqual(time_series_deaths_long.shape, (245385, 6))
    def test_03_merge_time_series_confirmed_deaths(self):
        merged_time_series = merge_time_series_confirmed_deaths()
        self.assertIsInstance(merged_time_series, pd.core.frame.DataFrame)
        self.assertEqual(merged_time_series.shape, (245385, 7))
    def test_04_replace_nan_in_province_state(self):
        nan_replaced = replace_nan_in_province_state()
        self.assertIsInstance(nan_replaced, pd.core.frame.DataFrame)
        self.assertEqual(nan_replaced["Province/State"].isnull().sum(), 0)
    def test_05_filter_taiwan_time_series(self):
        taiwan_time_series = filter_taiwan_time_series()
        self.assertIsInstance(taiwan_time_series, pd.core.frame.DataFrame)
        self.assertEqual(taiwan_time_series.shape, (861, 7))
        self.assertEqual((taiwan_time_series["Date"].astype(str).str.len() != 10).sum(), 0)
        self.assertEqual(taiwan_time_series["Province/State"].str.contains("*", regex=False).sum(), 0)
        self.assertEqual(taiwan_time_series["Country/Region"].str.contains("*", regex=False).sum(), 0)
    def test_06_calculate_daily_confirmed_deaths(self):
        daily_confirmed_deaths = calculate_daily_confirmed_deaths()
        self.assertIsInstance(daily_confirmed_deaths, pd.core.frame.DataFrame)
        self.assertEqual(daily_confirmed_deaths.shape, (861, 9))
    def test_07_filter_recent_pandemic_in_taiwan(self):
        recent_pandemic_in_taiwan = filter_recent_pandemic_in_taiwan()
        self.assertIsInstance(recent_pandemic_in_taiwan, pd.core.frame.DataFrame)
        self.assertEqual(recent_pandemic_in_taiwan.shape, (61, 9))
    def test_08_import_tables_in_nba_db(self):
        career_summaries, players, teams = import_tables_in_nba_db()
        self.assertIsInstance(career_summaries, pd.core.frame.DataFrame)
        self.assertIsInstance(players, pd.core.frame.DataFrame)
        self.assertIsInstance(teams, pd.core.frame.DataFrame)
        self.assertEqual(career_summaries.shape, (506, 31))
        self.assertEqual(players.shape, (506, 18))
        self.assertEqual(teams.shape, (30, 12))
    def test_09_list_roster_of_the_nba_playoffs_2022(self):
        roster_of_the_nba_playoffs_2022 = list_roster_of_the_nba_playoffs_2022()
        self.assertIsInstance(roster_of_the_nba_playoffs_2022, pd.core.frame.DataFrame)
        self.assertEqual(roster_of_the_nba_playoffs_2022.shape, (269, 4))
        self.assertEqual(roster_of_the_nba_playoffs_2022.iloc[:, 0].nunique(), 2)
        self.assertEqual(roster_of_the_nba_playoffs_2022.iloc[:, 1].nunique(), 16)
    def test_10_list_roster_of_the_nba_finals_2022(self):
        roster_of_the_nba_finals_2022 = list_roster_of_the_nba_finals_2022()
        self.assertIsInstance(roster_of_the_nba_finals_2022, pd.core.frame.DataFrame)
        self.assertEqual(roster_of_the_nba_finals_2022.shape, (34, 5))
        self.assertEqual(roster_of_the_nba_finals_2022.iloc[:, 0].nunique(), 2)
        self.assertEqual(roster_of_the_nba_finals_2022.iloc[:, 1].nunique(), 2)
        first_names = ["Jayson", "Jaylen", "Al", "Stephen", "Klay", "Andrew"]
        for first_name in first_names:
            self.assertIn(first_name, roster_of_the_nba_finals_2022.iloc[:, 2].values)
        
suite = unittest.TestLoader().loadTestsFromTestCase(TestFinal)
runner = unittest.TextTestRunner(verbosity=2)
test_results = runner.run(suite)
number_of_failures = len(test_results.failures)
number_of_errors = len(test_results.errors)
number_of_test_runs = test_results.testsRun
number_of_successes = number_of_test_runs - (number_of_failures + number_of_errors)

In [ ]:
print("You've got {} successes among {} questions.".format(number_of_successes, number_of_test_runs))